version: '3'
services:
  db:
    restart: always
    image: postgres:10
    env_file: .env
    expose:
      - 5432
    networks:
      - db_network
  gentelella:
    restart: always
    env_file: .env
    build: .
    ports:
      - "5000:5000"
    networks:
      - db_network
      - web_network
    depends_on:
      - db
  ngrok:
    container_name: ngrok
    ports:
      - "0.0.0.0:4040:4040"
    image: wernight/ngrok
    networks:
      - db_network
      - web_network
    depends_on:
       - gentelella
    links:
       - gentelella
    environment:
       - NGROK_PORT=gentelella:5000
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge